## **Global Monkeypox Prevalence Analysis**

This project is designed to answer a set of questions regarding the Monkeypox virus, which has been declared as a global public health emergency by the World Health Organization as of July, 2022.

The provided dataset contains the number of confirmed cases reported daily by country, as well as the cumulative cases each day.

The questions will be answered by statistical analysis of the data, and question solutions will be depicted by corresponding visualizations.

***Question 1a:*** What is the total number of countries observed in this dataset?

***Question 1b:*** Which countries are included?

***Question 2:*** What are the top 10 countries affected, by total case count?

***Question 3a:*** What is the mean number of cases for all countries observed?

***Question 3b:*** What is the median?

***Question 4:*** What is the sum of global cases to date?

***Question 5a:*** Which ten countries were the earliest cases reported in this year?

***Question 5b:*** Where and when was the earliest report of a confirmed case in the available dataset?

Data Source: https://github.com/globaldothealth/monkeypox/blob/main/timeseries-country-confirmed.csv
Date Downloaded: 08/08/2022

In [1]:
import pandas as pd

In [2]:
#Opens the data csv file and creates as dataframe; previews result
MPX_data = pd.read_csv(r'C:\Users\Domanic\Desktop\MPX-8-08-2022.csv')
MPX_data

            Date  Cases  Cumulative_cases    Country
0     2022-07-25      1                 1    Andorra
1     2022-07-26      2                 3    Andorra
2     2022-07-27      0                 3    Andorra
3     2022-07-28      0                 3    Andorra
4     2022-07-29      0                 3    Andorra
...          ...    ...               ...        ...
4851  2022-08-04      0                 1  Venezuela
4852  2022-08-05      0                 1  Venezuela
4853  2022-08-06      0                 1  Venezuela
4854  2022-08-07      0                 1  Venezuela
4855  2022-08-08      0                 1  Venezuela

[4856 rows x 4 columns]

In [3]:
#Question 1a
#Outputs the number of countries observed, and an alphabetized list
countryArr = MPX_data['Country'].unique()
numCountries = len(countryArr)
print(str(numCountries)+str(' countries were observed in this dataset.'))

#Question 1b
#Outputs countries as an alphabetized list
countryList = list(countryArr)
print('In alphabetized order, they are:\n')
number = 0
for country in countryList:
    number+=1
    print(str(number)+'.', country)

89 countries were observed in this dataset.
In alphabetized order, they are:

1. Andorra
2. Argentina
3. Australia
4. Austria
5. Barbados
6. Belgium
7. Benin
8. Bermuda
9. Bolivia
10. Bosnia And Herzegovina
11. Brazil
12. Bulgaria
13. Cameroon
14. Canada
15. Central African Republic
16. Chile
17. China
18. Colombia
19. Costa Rica
20. Croatia
21. Cyprus
22. Czech Republic
23. Democratic Republic Of The Congo
24. Denmark
25. Dominican Republic
26. Ecuador
27. Estonia
28. Finland
29. France
30. Georgia
31. Germany
32. Ghana
33. Gibraltar
34. Greece
35. Guadeloupe
36. Guatemala
37. Hungary
38. Iceland
39. India
40. Ireland
41. Israel
42. Italy
43. Jamaica
44. Japan
45. Latvia
46. Lebanon
47. Liberia
48. Lithuania
49. Luxembourg
50. Malta
51. Martinique
52. Mexico
53. Montenegro
54. Morocco
55. Netherlands
56. New Caledonia
57. New Zealand
58. Nigeria
59. Norway
60. Panama
61. Peru
62. Philippines
63. Poland
64. Portugal
65. Puerto Rico
66. Qatar
67. Republic of Congo
68. Romania
69. Russia
70. Saint Martin (French part)
71. Saudi Arabia
72. Serbia
73. Singapore
74. Slovakia
75. Slovenia
76. South Africa
77. South Korea
78. Spain
79. Sudan
80. Sweden
81. Switzerland
82. Taiwan
83. Thailand
84. Turkey
85. United Arab Emirates
86. United Kingdom
87. United States
88. Uruguay
89. Venezuela

In [4]:
#Question 2
#Outputs the top ten affected countries by cumulative cases this year
casesSum = MPX_data.groupby('Country')['Cases'].sum().sort_values(ascending=False)
topTen = casesSum.head(10)
print(str('The top 10 countries by cumulative cases:\n\n'), topTen.to_string())

The top 10 countries by cumulative cases:

 Country
United States     7492
Spain             4942
Germany           2887
United Kingdom    2859
France            2423
Brazil            2004
Canada             957
Netherlands        957
Portugal           710
Italy              545

In [5]:
#Question 3a
#Displays the mean number of cumulative cases for all countries observed
casesMean = MPX_data.groupby('Country')['Cases'].sum().mean()
print('The mean number of cases for all {} countries observed is: '.format(numCountries), round(casesMean, 2))

#Question 3b
#Outputs the median number of cumulative cases for all countries observed
#For an even number of countries, identifies median positions and averages their values
med1 = int((numCountries/2))
med2 = int((numCountries/2)+1)
calcMed = (casesSum[med1]+casesSum[med2])/2

if ((numCountries)%2) == 0:
    print('The index values for calculating the median are: '+str(med1)+', '+str(med2))
    print('The median for cumulative cases is '+str(calcMed)+', calculated as the mean of the values from '+str(casesSum.index[med1])+' and '+str(casesSum.index[med2]))
else:
    print('The index value of the median is: ', (numCountries+1)/2)
    print('The median country is '+str(casesSum.index[med1])+', with '+str(casesSum.iloc[int((numCountries+1)/2)])+' cumulative cases')

The mean number of cases for all 89 countries observed is:  323.07
The index value of the median is:  45.0
The median country is Central African Republic, with 7 cumulative cases

In [6]:
#Question 4
#Outputs cumulative number of confirmed cases globally
print('At present, the total number of confirmed cases for all countries worldwide is '+str(casesSum.sum()))

At present, the total number of confirmed cases for all countries worldwide is 28753

In [7]:
#Question 5a
#Prints countries ordered by earliest recorded case in 2022
earliest = MPX_data.groupby('Country')['Date'].min().sort_values().head(10)
#print('Earliest confirmed cases in 2022, by country: \n'+str(earliest))
print('Ten earliest confirmed countries in 2022: \n\n', earliest.to_string())

#Question 5b
#Returns earliest confirmed case in 2022, and the country it was recorded in
print('\nThe first recorded case of 2022 was in '+str(earliest.index[0])+str(' on ')+str(earliest[0]))

Ten earliest confirmed countries in 2022:

 Country
Nigeria                             2022-01-31
Cameroon                            2022-02-17
Central African Republic            2022-03-04
Republic of Congo                   2022-04-12
United Kingdom                      2022-05-06
Democratic Republic Of The Congo    2022-05-08
Portugal                            2022-05-17
United States                       2022-05-18
Spain                               2022-05-18
Belgium                             2022-05-19

The first recorded case of 2022 was in Nigeria on 2022-01-31